version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-php
    image: fullcycle/php
    working_dir: /var/www
    volumes:
    - ./:/var/www
    networks:
    - app-php

  nginx:
    build: .docker/nginx
    container_name: app-nginx
    ports:
      - 8888:80
      - 444:443
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/confi.d/default.conf
    networks:
      - app-php

networks:
  app-php:
    driver: bridge
